import { Program, Node as ESNode } from "estree";
import { generate, attachComments } from "escodegen";
// TODO: fix this so it's
// import Cast from '@scratch2js/util'
import Cast from "../../util";
import { readFileSync } from "fs";
import { SB3Project } from "./project";
import { processTarget } from "./processTarget";
class Compiler {
  static transpile(project: SB3Project) {
    return (
      "// Generated by scratch2js (https://github.com/elimerl/scratch2js)\n" +
      generate(new this().transpile(project))
    );
  }
  /**
   * Transpile a scratch project to an ESTree AST.
   */
  public transpile(project: SB3Project): Program {
    const ast: Program = { body: [], sourceType: "module", type: "Program" };
    project.targets.forEach((target) => {
      //@ts-expect-error
      ast.body.push(...processTarget(target));
    });
    return ast;
  }
}
const project = JSON.parse(readFileSync("testproject.json").toString());
console.log(Compiler.transpile(project));
